root: true
parser: '@typescript-eslint/parser'
parserOptions:
  tsconfigRootDir: __dirname
extends:
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:prettier/recommended'
plugins:
  - html
  - import
  - prettier
  - '@typescript-eslint'
  - jsx-a11y
  - react
  - react-hooks
rules:
  no-use-before-define: 'off'
  prettier/prettier: error
  no-restricted-imports:
    - error
  no-redeclare: error
  import/no-anonymous-default-export: off
  '@typescript-eslint/no-redeclare':
    - error
  '@typescript-eslint/no-unused-vars': warn
  '@typescript-eslint/no-explicit-any': warn
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: warn